### ISSUE TITLE
Upgrade deprecated rust crate

### ISSUE THREAD

**Issue by penguin-wwy** [AntChainOpenLabs/Smart-Intermediate-Representation#26]
My compilation environment is `Apple M1 Pro + llvm14.06`, and then reports the following error:
```
  = note: ld: in /code/Smart-Intermediate-Representation/ir_cli/target/debug/deps/libcrypto-0c982123f184820d.rlib(util_helpers.o), archive member 'util_helpers.o' with length 3584 is not mach-o or llvm bitcode file '/code/Smart-Intermediate-Representation/ir_cli/target/debug/deps/libcrypto-0c982123f184820d.rlib' for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't know why `./target/debug/build/rust-crypto-a1d6e5bc04f40d1d/out/src/util_helpers.o` would be compiled to x86_64 with the full aarch64 toolchain environment.

```
./target/debug/build/rust-crypto-a1d6e5bc04f40d1d/out/src/util_helpers.o: Mach-O 64-bit object x86_64
```

After that, I confirmed that this problem exists only in `rust-crypto` among all dependencies.

`rust-crypto` is unmaintained for at least 2020, https://rustsec.org/advisories/RUSTSEC-2016-0005.html

One possible fix is to use [sha2](https://docs.rs/sha2/latest/sha2/) instead of `rust-crypto`, updating the sha256 function, and the `make` command is successfully executed in my environment.

I can submit a PR to show my changes if needed.

**Comment by i-zhen** [comment]
Thank you for your kindly issue!
We are very pleased to welcome you to contribute to the project.

However, we are upgrading llvm 14 to llvm 15 for u256 support recently (we will upgrade both docker CI and opaque pointer in codegen).

Thus, you can submit your PR after migration of llvm.
